module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  block: 0
  block_content: 0
  breakpoint: 0
  config: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  dblog: 0
  editor: 0
  entity: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gnode: 0
  google_api_client: 0
  google_photos_importer: 0
  group: 0
  groupmedia: 0
  image: 0
  link: 0
  media: 0
  media_entity_remote_google_photos: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  path: 0
  path_alias: 0
  range: 0
  rest: 0
  serialization: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  typed_data: 0
  user: 0
  variationcache: 0
  views_bulk_operations: 0
  views_bulk_operations_example: 0
  views_ui: 0
  webform: 0
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  bartik: 0
  seven: 0
  bootstrap_barrio: 0
  quiz5_subtheme: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
